env:
  browser: true
  es2021: true
  node: true

extends:
  - plugin:react/recommended
  - standard-with-typescript
  - next

overrides: []
parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

rules: {
  "@typescript-eslint/explicit-function-return-type": off
}
