name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node ${{ matrix.nodejs }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        nodejs: [
          14, 
          16, 
          18
        ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Test
      run: yarn test
