name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        nodejs: [16]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm install

    - name: Compiles
      run: npm run build

    - name: Type Checks
      run: npm run types

    - name: Tests <~ ESM
      run: node --loader ./dist/loader/index.js test/index.mjs

    - name: Tests <~ ESM <~ TypeScript
      run: node --loader ./dist/loader/index.js test/config/index.ts --tsmconfig test/config/tsm.js

    - name: Tests <~ CLI
      run: ./dist/index.js test/index.mjs

    - name: Tests <~ CLI <~ TypeScript
      run: ./dist/index.js test/config/index.ts --tsmconfig test/config/tsm.js
